version: '3'
services:
    proxy:
        build: ./proxy
        image: proxyapp:latest
        ports:
        - "443:443"
        - "80:80"
    web:
        build: ./web
        image: webapp:latest
        expose:
        - "8080"
